[profile.default]
solc-version = "0.8.30"
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'paris'

[profile.networks]
base.url = "wss://base-rpc.publicnode.com"
mainnet.chain_id = 8453

[etherscan]
base = { key = "${BAK}" }
